<?php

namespace ContainerXAh7nec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateMatchService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Manager\GenerateMatch' shared autowired service.
     *
     * @return \App\Manager\GenerateMatch
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Manager\\GenerateMatch'] = new \App\Manager\GenerateMatch(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
