<?php

namespace ContainerXAh7nec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SportRepository' shared autowired service.
     *
     * @return \App\Repository\SportRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SportRepository'] = new \App\Repository\SportRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
