services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      APP_ENV: ${APP_ENV}
    command: ["/bin/bash", "-c", "/usr/local/bin/init.sh && apache2-foreground"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}

  npm:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "npm", "run", "watch" ]

volumes:
  vendor: