services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      APP_ENV: "prod"
    command: ["/bin/bash", "-c", "/usr/local/bin/init.sh && apache2-foreground"]

volumes:
  vendor:
