services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db -- /usr/local/bin/init.sh && apache2-foreground"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env.local

  npm:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "npm", "run", "watch" ]

volumes:
  vendor: