services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=prod
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    command: [ "sh", "-c", "/usr/local/bin/init.sh && apache2-foreground" ]

volumes:
  vendor:
