services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: "prod"
    command: ["/bin/bash", "-c", "/usr/local/bin/init.sh && apache2-foreground"]
