<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Tournament__CLASSMETADATA__' => 0,
'App__Entity__Sport__CLASSMETADATA__' => 1,
'App__Entity__Team__CLASSMETADATA__' => 2,
'App__Entity__User__CLASSMETADATA__' => 3,
'App__Entity__TeamMatchResult__CLASSMETADATA__' => 4,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Tournament',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TournamentRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                        'date' => $o[3],
                        'location' => $o[4],
                        'metadata' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'date' => 'date',
                        'location' => 'location',
                        'metadata' => 'metadata',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'date' => 'date',
                        'location' => 'location',
                        'metadata' => 'metadata',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tournament',
                    ],
                ],
                'associationMappings' => [
                    [
                        'sport' => $o[6],
                        'teams' => $o[8],
                        'teamMatchResults' => $o[9],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Tournament',
                    7 => 'sport_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                    'string',
                    'json',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                    'date',
                    'location',
                    'metadata',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'date',
                    'location',
                    'metadata',
                ],
                'length' => [
                    2 => 255,
                    4 => 255,
                ],
                'nullable' => [
                    3 => true,
                    5 => true,
                ],
                'fetch' => [
                    6 => 2,
                    8 => 2,
                    2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\Tournament',
                    8 => 'App\\Entity\\Tournament',
                    'App\\Entity\\Tournament',
                ],
                'inversedBy' => [
                    6 => 'tournaments',
                ],
                'sourceToTargetKeyColumns' => [
                    6 => [
                        'sport_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    6 => [
                        'id' => 'sport_id',
                    ],
                ],
                'joinColumns' => [
                    6 => [
                        $o[7],
                    ],
                ],
                'joinColumnFieldNames' => [
                    6 => [
                        'sport_id' => 'sport_id',
                    ],
                ],
                'referencedColumnName' => [
                    7 => 'id',
                ],
                'mappedBy' => [
                    8 => 'tournament',
                    'tournament',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'sport',
                    8 => 'teams',
                    'teamMatchResults',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Sport',
                    8 => 'App\\Entity\\Team',
                    'App\\Entity\\TeamMatchResult',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Sport',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SportRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'sport',
                    ],
                ],
                'associationMappings' => [
                    [
                        'tournaments' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\Sport',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\Sport',
                ],
                'mappedBy' => [
                    3 => 'sport',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'tournaments',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\Tournament',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Team',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TeamRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'team',
                    ],
                ],
                'associationMappings' => [
                    [
                        'tournament' => $o[3],
                        'visitorMatches' => $o[5],
                        'homeMatches' => $o[6],
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'name' => [
                    'App\\Entity\\Team',
                    4 => 'tournament_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                    5 => 2,
                    2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\Team',
                    5 => 'App\\Entity\\Team',
                    'App\\Entity\\Team',
                ],
                'inversedBy' => [
                    3 => 'teams',
                ],
                'sourceToTargetKeyColumns' => [
                    3 => [
                        'tournament_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    3 => [
                        'id' => 'tournament_id',
                    ],
                ],
                'joinColumns' => [
                    3 => [
                        $o[4],
                    ],
                ],
                'joinColumnFieldNames' => [
                    3 => [
                        'tournament_id' => 'tournament_id',
                    ],
                ],
                'referencedColumnName' => [
                    4 => 'id',
                ],
                'mappedBy' => [
                    5 => 'visitor',
                    'home',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'tournament',
                    5 => 'visitorMatches',
                    'homeMatches',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\Tournament',
                    5 => 'App\\Entity\\TeamMatchResult',
                    'App\\Entity\\TeamMatchResult',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'username' => $o[2],
                        'roles' => $o[3],
                        'password' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'users',
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_USERNAME' => [
                                'fields' => [
                                    'username',
                                ],
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[5],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'json',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'username',
                    'roles',
                    'password',
                ],
                'columnName' => [
                    1 => 'id',
                    'username',
                    'roles',
                    'password',
                ],
                'length' => [
                    2 => 180,
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\TeamMatchResult',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TeamMatchResultRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'visitorScore' => $o[2],
                        'homeScore' => $o[3],
                        'phase' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'visitor_score' => 'visitorScore',
                        'home_score' => 'homeScore',
                        'phase' => 'phase',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'visitorScore' => 'visitor_score',
                        'homeScore' => 'home_score',
                        'phase' => 'phase',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'team_match_result',
                    ],
                ],
                'associationMappings' => [
                    [
                        'tournament' => $o[5],
                        'visitor' => $o[7],
                        'home' => $o[9],
                        'winner' => $o[11],
                    ],
                ],
                'idGenerator' => [
                    $o[13],
                ],
                'name' => [
                    'App\\Entity\\TeamMatchResult',
                    6 => 'tournament_id',
                    8 => 'visitor_id',
                    10 => 'home_id',
                    12 => 'winner_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'visitorScore',
                    'homeScore',
                    'phase',
                ],
                'columnName' => [
                    1 => 'id',
                    'visitor_score',
                    'home_score',
                    'phase',
                ],
                'nullable' => [
                    2 => true,
                    true,
                ],
                'length' => [
                    4 => 255,
                ],
                'fetch' => [
                    5 => 2,
                    7 => 2,
                    9 => 2,
                    11 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\TeamMatchResult',
                    7 => 'App\\Entity\\TeamMatchResult',
                    9 => 'App\\Entity\\TeamMatchResult',
                    11 => 'App\\Entity\\TeamMatchResult',
                ],
                'inversedBy' => [
                    5 => 'teamMatchResults',
                ],
                'sourceToTargetKeyColumns' => [
                    5 => [
                        'tournament_id' => 'id',
                    ],
                    7 => [
                        'visitor_id' => 'id',
                    ],
                    9 => [
                        'home_id' => 'id',
                    ],
                    11 => [
                        'winner_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    5 => [
                        'id' => 'tournament_id',
                    ],
                    7 => [
                        'id' => 'visitor_id',
                    ],
                    9 => [
                        'id' => 'home_id',
                    ],
                    11 => [
                        'id' => 'winner_id',
                    ],
                ],
                'joinColumns' => [
                    5 => [
                        $o[6],
                    ],
                    7 => [
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                    ],
                    11 => [
                        $o[12],
                    ],
                ],
                'joinColumnFieldNames' => [
                    5 => [
                        'tournament_id' => 'tournament_id',
                    ],
                    7 => [
                        'visitor_id' => 'visitor_id',
                    ],
                    9 => [
                        'home_id' => 'home_id',
                    ],
                    11 => [
                        'winner_id' => 'winner_id',
                    ],
                ],
                'referencedColumnName' => [
                    6 => 'id',
                    8 => 'id',
                    10 => 'id',
                    12 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'tournament',
                    7 => 'visitor',
                    9 => 'home',
                    11 => 'winner',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\Tournament',
                    7 => 'App\\Entity\\Team',
                    9 => 'App\\Entity\\Team',
                    11 => 'App\\Entity\\Team',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
