<?php

namespace ContainerMiv7J3S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeploymentControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Deploy\DeploymentController' shared autowired service.
     *
     * @return \App\Controller\Deploy\DeploymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Deploy\\DeploymentController'] = $instance = new \App\Controller\Deploy\DeploymentController(($container->services['console.command.public_alias.App\\Command\\ImportSportsCommand'] ?? $container->load('getImportSportsCommandService')), ($container->services['console.command.public_alias.App\\Command\\ImportUserCommand'] ?? $container->load('getImportUserCommandService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\Deploy\\DeploymentController', $container));

        return $instance;
    }
}
