<?php

namespace ContainerMiv7J3S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentFilterTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TournamentFilterType' shared autowired service.
     *
     * @return \App\Form\TournamentFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TournamentFilterType'] = new \App\Form\TournamentFilterType();
    }
}
