<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2X8X34\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2X8X34/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL2X8X34.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL2X8X34\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerL2X8X34\App_KernelProdContainer([
    'container.build_hash' => 'L2X8X34',
    'container.build_id' => 'b8a41734',
    'container.build_time' => 1741778639,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2X8X34');
