<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzC7oxq\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzC7oxq/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXzC7oxq.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXzC7oxq\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXzC7oxq\App_KernelProdContainer([
    'container.build_hash' => 'XzC7oxq',
    'container.build_id' => '723b695b',
    'container.build_time' => 1741777715,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzC7oxq');
