<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiv7J3S\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiv7J3S/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMiv7J3S.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMiv7J3S\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMiv7J3S\App_KernelProdContainer([
    'container.build_hash' => 'Miv7J3S',
    'container.build_id' => '9dd7f9ef',
    'container.build_time' => 1741871940,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiv7J3S');
