<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.ced75ccf.js',
                '/build/958.0685a08e.js',
                '/build/app.b824bf06.js',
            ],
        ],
        'timer' => [
            'js' => [
                '/build/runtime.ced75ccf.js',
                '/build/958.0685a08e.js',
                '/build/timer.08d63012.js',
            ],
        ],
        'app_css' => [
            'js' => [
                '/build/runtime.ced75ccf.js',
            ],
            'css' => [
                '/build/app_css.5eef0bf3.css',
            ],
        ],
        'aside_css' => [
            'js' => [
                '/build/runtime.ced75ccf.js',
            ],
            'css' => [
                '/build/aside_css.624a0b58.css',
            ],
        ],
        'tournament_css' => [
            'js' => [
                '/build/runtime.ced75ccf.js',
            ],
            'css' => [
                '/build/tournament_css.93d45b1d.css',
            ],
        ],
    ],
],

]];
