<?php

namespace ContainerHR3vxU8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentControllerupdateScoresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.70z8CdC.App\Controller\TournamentController::updateScores()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.70z8CdC.App\\Controller\\TournamentController::updateScores()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournament' => ['privates', '.errored..service_locator.70z8CdC.App\\Entity\\Tournament', NULL, 'Cannot autowire service ".service_locator.70z8CdC": it needs an instance of "App\\Entity\\Tournament" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournament' => 'App\\Entity\\Tournament',
        ]))->withContext('App\\Controller\\TournamentController::updateScores()', $container);
    }
}
