<?php

namespace ContainerAmbYfQ5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PE_FlFuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pE.FlFu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pE.FlFu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'teamMatchResultRepository' => ['privates', 'App\\Repository\\TeamMatchResultRepository', 'getTeamMatchResultRepositoryService', true],
        ], [
            'teamMatchResultRepository' => 'App\\Repository\\TeamMatchResultRepository',
        ]);
    }
}
