<?php

namespace ContainerXzC7oxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeploymentControllerdeployService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.p9aoVBE.App\Controller\Deploy\DeploymentController::deploy()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p9aoVBE.App\\Controller\\Deploy\\DeploymentController::deploy()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dependencyFactory' => ['privates', '.errored..service_locator.p9aoVBE.Doctrine\\Migrations\\DependencyFactory', NULL, 'Cannot autowire service ".service_locator.p9aoVBE": it references class "Doctrine\\Migrations\\DependencyFactory" but no such service exists. You should maybe alias this class to the existing "doctrine.migrations.dependency_factory" service.'],
        ], [
            'dependencyFactory' => 'Doctrine\\Migrations\\DependencyFactory',
        ]))->withContext('App\\Controller\\Deploy\\DeploymentController::deploy()', $container);
    }
}
