<?php

namespace ContainerXzC7oxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.pE.FlFu.App\Controller\DefaultController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pE.FlFu.App\\Controller\\DefaultController::index()'] = ($container->privates['.service_locator.pE.FlFu'] ?? $container->load('get_ServiceLocator_PE_FlFuService'))->withContext('App\\Controller\\DefaultController::index()', $container);
    }
}
