<?php

namespace ContainerXzC7oxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDependencyFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.p9aoVBE.Doctrine\Migrations\DependencyFactory' shared service.
     *
     * @return \Doctrine\Migrations\DependencyFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.p9aoVBE": it references class "Doctrine\\Migrations\\DependencyFactory" but no such service exists. You should maybe alias this class to the existing "doctrine.migrations.dependency_factory" service.');
    }
}
