<?php

namespace ContainerL2X8X34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamCollectionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TeamCollectionType' shared autowired service.
     *
     * @return \App\Form\TeamCollectionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TeamCollectionType'] = new \App\Form\TeamCollectionType();
    }
}
