<?php

namespace ContainerL2X8X34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Video\VideoController' shared autowired service.
     *
     * @return \App\Controller\Video\VideoController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Video\\VideoController'] = $instance = new \App\Controller\Video\VideoController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\Video\\VideoController', $container));

        return $instance;
    }
}
