<?php

namespace ContainerIEGsrAV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9bLkeNaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9bLkeNa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9bLkeNa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.pE.FlFu.App\\Controller\\DefaultController::index()', 'getDefaultControllerindexService', true],
            'App\\Controller\\Deploy\\DeploymentController::deploy' => ['privates', '.service_locator.p9aoVBE.App\\Controller\\Deploy\\DeploymentController::deploy()', 'getDeploymentControllerdeployService', true],
            'App\\Controller\\Security\\RegistrationController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\Security\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\Security\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\Security\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TeamMatchResultController::index' => ['privates', '.service_locator.pE.FlFu.App\\Controller\\TeamMatchResultController::index()', 'getTeamMatchResultControllerindexService', true],
            'App\\Controller\\TournamentController::updateScores' => ['privates', '.service_locator.70z8CdC.App\\Controller\\TournamentController::updateScores()', 'getTournamentControllerupdateScoresService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.pE.FlFu.App\\Controller\\DefaultController::index()', 'getDefaultControllerindexService', true],
            'App\\Controller\\Deploy\\DeploymentController:deploy' => ['privates', '.service_locator.p9aoVBE.App\\Controller\\Deploy\\DeploymentController::deploy()', 'getDeploymentControllerdeployService', true],
            'App\\Controller\\Security\\RegistrationController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\Security\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\Security\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\Security\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TeamMatchResultController:index' => ['privates', '.service_locator.pE.FlFu.App\\Controller\\TeamMatchResultController::index()', 'getTeamMatchResultControllerindexService', true],
            'App\\Controller\\TournamentController:updateScores' => ['privates', '.service_locator.70z8CdC.App\\Controller\\TournamentController::updateScores()', 'getTournamentControllerupdateScoresService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DefaultController::index' => '?',
            'App\\Controller\\Deploy\\DeploymentController::deploy' => '?',
            'App\\Controller\\Security\\RegistrationController::register' => '?',
            'App\\Controller\\Security\\SecurityController::login' => '?',
            'App\\Controller\\TeamMatchResultController::index' => '?',
            'App\\Controller\\TournamentController::updateScores' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DefaultController:index' => '?',
            'App\\Controller\\Deploy\\DeploymentController:deploy' => '?',
            'App\\Controller\\Security\\RegistrationController:register' => '?',
            'App\\Controller\\Security\\SecurityController:login' => '?',
            'App\\Controller\\TeamMatchResultController:index' => '?',
            'App\\Controller\\TournamentController:updateScores' => '?',
        ]);
    }
}
