<?php

namespace ContainerIEGsrAV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeploymentControllerdeployService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p9aoVBE.App\Controller\Deploy\DeploymentController::deploy()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p9aoVBE.App\\Controller\\Deploy\\DeploymentController::deploy()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dependencyFactory' => ['privates', 'doctrine.migrations.dependency_factory', 'getDoctrine_Migrations_DependencyFactoryService', true],
        ], [
            'dependencyFactory' => '?',
        ]))->withContext('App\\Controller\\Deploy\\DeploymentController::deploy()', $container);
    }
}
