<?php

namespace ContainerHoXxqx1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TournamentController' shared autowired service.
     *
     * @return \App\Controller\TournamentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TournamentController.php';

        $container->services['App\\Controller\\TournamentController'] = $instance = new \App\Controller\TournamentController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Manager\\GenerateMatch'] ?? $container->load('getGenerateMatchService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\TournamentController', $container));

        return $instance;
    }
}
