<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBaxmXqh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBaxmXqh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBaxmXqh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBaxmXqh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBaxmXqh\App_KernelDevDebugContainer([
    'container.build_hash' => 'BaxmXqh',
    'container.build_id' => 'e0ed3893',
    'container.build_time' => 1741871637,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBaxmXqh');
