<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHR3vxU8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHR3vxU8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHR3vxU8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHR3vxU8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHR3vxU8\App_KernelDevDebugContainer([
    'container.build_hash' => 'HR3vxU8',
    'container.build_id' => '92eb4cdb',
    'container.build_time' => 1741871866,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHR3vxU8');
