<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzss0B5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzss0B5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPzss0B5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPzss0B5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPzss0B5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pzss0B5',
    'container.build_id' => 'b174c623',
    'container.build_time' => 1741767725,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzss0B5');
