<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournament extends \App\Entity\Tournament implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'sport' => [parent::class, 'sport', null],
        "\0".parent::class."\0".'teamMatchResults' => [parent::class, 'teamMatchResults', null],
        "\0".parent::class."\0".'teams' => [parent::class, 'teams', null],
        'date' => [parent::class, 'date', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'metadata' => [parent::class, 'metadata', null],
        'name' => [parent::class, 'name', null],
        'sport' => [parent::class, 'sport', null],
        'teamMatchResults' => [parent::class, 'teamMatchResults', null],
        'teams' => [parent::class, 'teams', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
