<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TeamMatchResult extends \App\Entity\TeamMatchResult implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'home' => [parent::class, 'home', null],
        "\0".parent::class."\0".'homeScore' => [parent::class, 'homeScore', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'phase' => [parent::class, 'phase', null],
        "\0".parent::class."\0".'tournament' => [parent::class, 'tournament', null],
        "\0".parent::class."\0".'visitor' => [parent::class, 'visitor', null],
        "\0".parent::class."\0".'visitorScore' => [parent::class, 'visitorScore', null],
        "\0".parent::class."\0".'winner' => [parent::class, 'winner', null],
        'home' => [parent::class, 'home', null],
        'homeScore' => [parent::class, 'homeScore', null],
        'id' => [parent::class, 'id', null],
        'phase' => [parent::class, 'phase', null],
        'tournament' => [parent::class, 'tournament', null],
        'visitor' => [parent::class, 'visitor', null],
        'visitorScore' => [parent::class, 'visitorScore', null],
        'winner' => [parent::class, 'winner', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
